from typing import Any, Protocol


class FinanceRepository(Protocol):
    def get_accounts_summary(self, tenant_id: str) -> dict[str, Any]: ...
    def get_month_balance(self, month: int, year: int, tenant_id: str) -> dict[str, Any]: ...
    def list_active_debts(self, tenant_id: str) -> list[dict[str, Any]]: ...
    def list_transactions(self, tenant_id: str) -> list[dict[str, Any]]: ...
    def list_categories(self, tenant_id: str, category_type: str | None = None) -> list[dict[str, Any]]: ...
    def create_category_if_missing(self, tenant_id: str, name: str, category_type: str, subcategories: str = "") -> dict[str, Any]: ...
    def list_pending_movements(self, tenant_id: str, limit: int = 50, include_resolved: bool = False) -> list[dict[str, Any]]: ...
    def create_transaction(self, tenant_id: str, payload: dict[str, Any]) -> str: ...
    def update_transaction(self, tenant_id: str, transaction_id: str, field: str, value: Any) -> Any: ...
    def delete_transaction(self, tenant_id: str, transaction_id: str) -> Any: ...
    def pay_debt(self, tenant_id: str, debt_id: str, payload: dict[str, Any]) -> Any: ...
    def confirm_pending_movement(self, tenant_id: str, pending_id: str, category: str, note: str = "") -> Any: ...
    def discard_pending_movement(self, tenant_id: str, pending_id: str, reason: str = "") -> Any: ...
    def create_snapshot(self, tenant_id: str, origin: str = "Mobile", date: Any = None) -> Any: ...
